name: Rust

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

env:
  CARGO_TERM_COLOR: always
  RUST_LOG: info
  RUST_BACKTRACE: 1

jobs:
  build:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:15
        ports:
          - 5432:5432
        env:
          POSTGRES_USER: r2p
          POSTGRES_PASSWORD: ypassword
          POSTGRES_DB: zero2prod
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - uses: actions/checkout@v4
      - name: Make envfile
        uses: SpicyPizza/create-envfile@v2.0
        with:
          envkey_DATABASE_URL: "postgresql://r2p:ypassword@localhost:5432/zero2prod"
      - name: Migrate database
        run: |
          cargo install --version=0.8.6 sqlx-cli --no-default-features --features postgres,native-tls
          cargo sqlx database create
          cargo sqlx migrate run
      - name: Run tests
        run: cargo test
